import { StyleSheet, Dimensions } from "react-native";

const { width, height } = Dimensions.get('window');

export const home_styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#F5F5F5',
    },
    header: {
        backgroundColor: '#0C352E',
        paddingHorizontal: width * 0.05,
        paddingTop: 20,
        paddingBottom: 100,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    headerText: {
        flex: 1,
    },
    greeting: {
        fontSize: width * 0.045,
        color: '#FFFFFF',
        marginBottom: 4,
    },
    userName: {
        fontSize: width * 0.07,
        fontWeight: '700' as '700',
        color: '#FFFFFF',
    },
    avatar: {
        width: 56,
        height: 56,
        borderRadius: 28,
        backgroundColor: '#D7D9CF',
    },
    content: {
        flex: 1,
        paddingHorizontal: width * 0.05,
        marginTop: -70,
    },
    totalCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 20,
        padding: 20,
        marginBottom: 16,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.12,
        shadowRadius: 12,
        elevation: 5,
    },
    totalLabel: {
        fontSize: width * 0.042,
        color: '#232323',
        textAlign: 'center',
        marginBottom: 12,
        fontWeight: '500' as '500',
    },
    totalAmount: {
        fontSize: width * 0.075,
        fontWeight: '700' as '700',
        color: '#232323',
        textAlign: 'center',
        marginBottom: 20,
    },
    statsRow: {
        flexDirection: 'row',
        justifyContent: 'space-around',
        paddingTop: 16,
        borderTopWidth: 1,
        borderTopColor: '#F0F0F0',
    },
    stat: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    statNumber: {
        fontSize: width * 0.045,
        fontWeight: '700' as '700',
        color: '#232323',
        marginRight: 4,
    },
    statLabel: {
        fontSize: width * 0.04,
        color: '#61646B',
    },
    performanceCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 16,
        padding: 16,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 16,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08,
        shadowRadius: 8,
        elevation: 3,
    },
    performanceLeft: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
    },
    performanceIcon: {
        width: 48,
        height: 48,
        borderRadius: 12,
        backgroundColor: '#E8F5F0',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 12,
    },
    performanceText: {
        flex: 1,
    },
    performanceTitle: {
        fontSize: width * 0.04,
        fontWeight: '600' as '600',
        color: '#232323',
        marginBottom: 4,
    },
    performanceSubtitle: {
        fontSize: width * 0.035,
        color: '#61646B',
    },
    performancePercentage: {
        fontSize: width * 0.04,
        fontWeight: '700' as '700',
        color: '#0C352E',
        position: 'absolute' as 'absolute',
    },
    progressCircle: {
        width: 56,
        height: 56,
        justifyContent: 'center',
        alignItems: 'center',
        position: 'relative' as 'relative',
    },
    addLeadButton: {
        backgroundColor: '#0C352E',
        borderRadius: 12,
        padding: 16,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 20,
    },
    addLeadText: {
        color: '#FFFFFF',
        fontSize: width * 0.04,
        fontWeight: '600' as '600',
        marginLeft: 8,
    },
    sectionHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 16,
        paddingBottom: 12,
        borderBottomWidth: 1,
        borderBottomColor: '#F0F0F0',
    },
    sectionTitle: {
        fontSize: width * 0.042,
        fontWeight: '600' as '600',
        color: '#232323',
    },
    addButton: {
        width: 24,
        height: 24,
        borderRadius: 12,
        borderWidth: 2,
        borderColor: '#232323',
        justifyContent: 'center',
        alignItems: 'center',
    },
    activitiesCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 16,
        padding: 16,
        marginBottom: 20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08,
        shadowRadius: 8,
        elevation: 3,
    },
    activityItem: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        marginBottom: 16,
    },
    activityIconContainer: {
        width: 40,
        height: 40,
        borderRadius: 20,
        borderWidth: 2,
        borderColor: '#0C352E',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 12,
    },
    activityLine: {
        position: 'absolute',
        left: 19,
        top: 40,
        width: 2,
        height: 20,
        backgroundColor: '#E0E0E0',
    },
    activityContent: {
        flex: 1,
        paddingTop: 4,
    },
    activityTitle: {
        fontSize: width * 0.04,
        fontWeight: '600' as '600',
        color: '#232323',
        marginBottom: 4,
    },
    activityTime: {
        fontSize: width * 0.035,
        color: '#61646B',
    },
    recentCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 16,
        padding: 16,
        marginBottom: 100,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08,
        shadowRadius: 8,
        elevation: 3,
    },
    recentItem: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingVertical: 12,
        borderBottomWidth: 1,
        borderBottomColor: '#F5F5F5',
    },
    recentLeft: {
        flex: 1,
    },
    recentName: {
        fontSize: width * 0.04,
        fontWeight: '600' as '600',
        color: '#232323',
        marginBottom: 4,
    },
    recentDescription: {
        fontSize: width * 0.035,
        color: '#61646B',
    },
    recentRight: {
        alignItems: 'flex-end',
    },
    statusBadge: {
        paddingHorizontal: 12,
        paddingVertical: 4,
        borderRadius: 12,
        borderWidth: 1,
        marginBottom: 4,
    },
    statusText: {
        fontSize: width * 0.03,
        fontWeight: '600' as '600',
    },
    timeAgo: {
        fontSize: width * 0.03,
        color: '#B0B0B0',
    },
});
