import { Dimensions, StyleSheet } from "react-native";

const { width } = Dimensions.get("window");

export const home_styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F0F1F3",
  },

  header: {
    backgroundColor: "#0C352E",
    paddingHorizontal: width * 0.03,
    paddingTop: 20,
    paddingBottom: 100,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  headerText: {
    flex: 1,
  },
  greeting: {
    fontSize: width * 0.045,
    color: "#FFFFFF",
    marginBottom: 4,
  },
  userName: {
    fontSize: width * 0.07,
    fontWeight: "700" as "700",
    color: "#FFFFFF",
  },
  avatar: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: "#D7D9CF",
  },
  content: {
    flex: 1,
    paddingHorizontal: width * 0.03,
    marginTop: -75,
  },
  totalCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 23,
    padding: 20,
    marginBottom: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    elevation: 5,
    zIndex: 5,
    shadowRadius: 12,
  },
  totalLabel: {
    fontSize: width * 0.042,
    color: "#2D3142",
    textAlign: "center",
    marginBottom: 12,
    fontWeight: "500" as "500",
  },
  totalAmount: {
    fontSize: width * 0.075,
    fontWeight: "700" as "700",
    color: "#0C352E",
    textAlign: "center",
    marginBottom: 20,
  },
  statsRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingTop: 16,
  },
  stat: {
    flexDirection: "row",
    alignItems: "center",
  },
  statNumber: {
    fontSize: width * 0.045,
    fontWeight: "700" as "700",
    color: "#0D352E",
    marginRight: 4,
  },
  statLabel: {
    fontSize: width * 0.04,
    color: "#0D352E",
  },
  performanceCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 23,
    padding: 16,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 3,
  },
  performanceLeft: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
  },
  performanceIcon: {
    width: 48,
    height: 48,
    borderRadius: 12,
    backgroundColor: "#A5C3BE",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
  },
  performanceText: {
    flex: 1,
  },
  performanceTitle: {
    fontSize: width * 0.04,
    fontWeight: "600" as "600",
    color: "#24252C",
    marginBottom: 4,
  },
  performanceSubtitle: {
    fontSize: width * 0.035,
    color: "#6E6A7C",
  },
  performancePercentage: {
    fontSize: width * 0.04,
    fontWeight: "700" as "700",
    color: "#0C352E",
    position: "absolute" as "absolute",
  },
  progressCircle: {
    width: 56,
    height: 56,
    justifyContent: "center",
    alignItems: "center",
    position: "relative" as "relative",
  },
  addLeadButton: {
    backgroundColor: "#0C352E",
    borderRadius: 18,
    padding: 18,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 16,
    position: "relative" as "relative",
  },
  addLeadText: {
    color: "#FFFFFF",
    fontSize: width * 0.04,
    fontWeight: "600" as "600",
    flex: 1,
    textAlign: "center" as "center",
  },
  addLeadIcon: {
    position: "absolute" as "absolute",
    left: 18,
  },
  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingBottom: 12,
  },
  sectionTitle: {
    fontSize: width * 0.042,
    fontWeight: "600" as "600",
    color: "#2D3142",
  },
  addButton: {
    width: 24,
    height: 24,
  },
  activitiesCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 23,
    padding: 16,
    marginBottom: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 3,
  },
  activityItem: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginBottom: 16,
  },
  activityIconContainer: {
    width: 40,
    height: 40,
    borderRadius: 20,
    borderWidth: 2,
    borderColor: "#0C352E",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
  },

  activityLine: {
    position: "absolute",
    left: 19,
    top: 40,
    width: 2,
    height: 25,
    backgroundColor: "#0C352E",
  },

  activityContent: {
    flex: 1,
    paddingTop: 4,
  },
  activityTitle: {
    fontSize: width * 0.04,
    fontWeight: "600" as "600",
    color: "#000000",
    marginBottom: 4,
  },
  activityTime: {
    fontSize: width * 0.035,
    color: "#7A7A7A",
  },
  recentCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 23,
    padding: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 3,
  },
  recentItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#F5F5F5",
  },
  recentLeft: {
    flex: 1,
  },
  recentName: {
    fontSize: width * 0.04,
    fontWeight: "600" as "600",
    color: "#2D3142",
    marginBottom: 4,
  },
  recentDescription: {
    fontSize: width * 0.035,
    color: "#99A1AF",
  },
  recentRight: {
    alignItems: "flex-end",
  },
  statusBadge: {
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 12,
    borderWidth: 1,
    marginBottom: 4,
  },
  statusText: {
    fontSize: width * 0.03,
    fontWeight: "600" as "600",
  },
  timeAgo: {
    fontSize: width * 0.03,
    color: "#D0D5DD",
  },
});
