import { StyleSheet, Dimensions, Platform } from "react-native";

const { width } = Dimensions.get('window');

export const sales_styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#F5F5F5',
    },
    header: {
        backgroundColor: '#0C352E',
        paddingVertical: 16,
        paddingHorizontal: 20,
        flexDirection: 'row',
        alignItems: 'center',
    },
    backButton: {
        padding: 4,
        marginRight: 12,
    },
    stepIndicatorContainer: {
        width: 72,
        height: 72,
        marginRight: 16,
        position: 'relative',
        justifyContent: 'center',
        alignItems: 'center',
    },
    progressCircleInner: {
        width: 64,
        height: 64,
        borderRadius: 32,
        backgroundColor: 'rgba(255, 255, 255, 0.1)',
        justifyContent: 'center',
        alignItems: 'center',
        paddingTop: 8,
    },
    stepNumber: {
        fontSize: 11,
        color: '#FFFFFF',
        fontWeight: '600' as '600',
        marginTop: 2,
    },
    headerTextContainer: {
        flex: 1,
    },
    headerTitle: {
        fontSize: 20,
        fontWeight: '600' as '600',
        color: '#FFFFFF',
        marginBottom: 2,
    },
    headerSubtitle: {
        fontSize: 13,
        color: 'rgba(255, 255, 255, 0.9)',
    },
    content: {
        flex: 1,
    },
    form: {
        padding: 20,
    },
    field: {
        marginBottom: 16,
    },
    label: {
        fontSize: 13,
        color: '#61646B',
        marginBottom: 8,
    },
    sectionTitle: {
        fontSize: 16,
        color: '#232323',
        marginBottom: 12,
        fontWeight: '600' as '600',
    },
    input: {
        backgroundColor: '#FFFFFF',
        borderWidth: 1,
        borderColor: '#E5E5E5',
        borderRadius: 12,
        paddingHorizontal: 16,
        height: 56,
        fontSize: 16,
        color: '#232323',
        marginBottom: 16,
    },
    mapContainer: {
        height: 400,
        backgroundColor: '#E5E5E5',
        borderRadius: 16,
        overflow: Platform.OS === 'ios' ? 'hidden' : 'visible',
        marginTop: 8,
        marginBottom: 16,
    },
    mapMarker: {
        width: 48,
        height: 48,
        borderRadius: 24,
        backgroundColor: '#0C352E',
        justifyContent: 'center',
        alignItems: 'center',
    },
    recheckButton: {
        position: 'absolute',
        bottom: 16,
        right: 16,
        width: 48,
        height: 48,
        borderRadius: 24,
        backgroundColor: '#FFFFFF',
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.15,
        shadowRadius: 4,
        elevation: 4,
    },
    alertCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        padding: 16,
        flexDirection: 'row',
        alignItems: 'flex-start',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08,
        shadowRadius: 8,
        elevation: 3,
    },
    alertIconContainer: {
        width: 44,
        height: 44,
        borderRadius: 22,
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 12,
    },
    alertTextContainer: {
        flex: 1,
    },
    alertTitle: {
        fontSize: 14,
        fontWeight: '600' as '600',
        color: '#232323',
        marginBottom: 4,
    },
    alertDescription: {
        fontSize: 13,
        color: '#61646B',
        lineHeight: 18,
    },
    buttonContainer: {
        padding: 20,
        backgroundColor: '#F5F5F5',
    },
    nextButton: {
        backgroundColor: '#0C352E',
        borderRadius: 12,
        height: 56,
        justifyContent: 'center',
        alignItems: 'center',
        marginHorizontal: 20,
        marginBottom: 20,
    },
    nextButtonText: {
        color: '#FFFFFF',
        fontSize: width * 0.04,
        fontWeight: '600',
    },
    headerContent: {
        flex: 1,
        alignItems: 'center',
    },
    stepIndicator: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    stepText: {
        color: '#FFFFFF',
        fontSize: 14,
        fontWeight: '500',
    },
    alertIcon: {
        marginRight: 8,
    },
    alertText: {
        color: '#FFFFFF',
        fontSize: 14,
    },
    textArea: {
        height: 120,
        paddingTop: 16,
        textAlignVertical: 'top',
    },
    inputWithIcon: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#FFFFFF',
        borderWidth: 1,
        borderColor: '#E5E5E5',
        borderRadius: 8,
        paddingHorizontal: 16,
        height: 50,
    },
    inputText: {
        flex: 1,
        fontSize: 14,
        color: '#232323',
    },
    pickerSmall: {
        width: 80,
        height: 48,
    },
    phoneInput: {
        flex: 1,
        fontSize: 14,
        color: '#232323',
        paddingHorizontal: 12,
    },
    pickerContainer: {
        flexDirection: 'row',
        backgroundColor: '#FFFFFF',
        borderWidth: 1,
        borderColor: '#E5E5E5',
        borderRadius: 12,
        height: 50,
        overflow: 'hidden',
    },
    picker: {
        flex: 1,
        height: 48,
    },
    signatureContainer: {
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        padding: 16,
        marginBottom: 20,
    },
    clearButton: {
        fontSize: 14,
        color: '#61646B',
    },
    totalCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        padding: 24,
        alignItems: 'center',
        marginBottom: 20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08,
        shadowRadius: 8,
        elevation: 3,
    },
    totalLabel: {
        fontSize: 16,
        color: '#61646B',
        marginBottom: 8,
    },
    totalAmount: {
        fontSize: 28,
        fontWeight: '700' as '700',
        color: '#232323',
    },
    paymentsHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 16,
    },
    paymentsSection: {
        marginBottom: 16,
    },
    paymentsTitle: {
        fontSize: 16,
        fontWeight: '600' as '600',
        color: '#232323',
    },
    addPaymentButton: {
        width: 32,
        height: 32,
        borderRadius: 16,
        borderWidth: 2,
        borderColor: '#232323',
        justifyContent: 'center',
        alignItems: 'center',
    },
    paymentCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        padding: 16,
        marginBottom: 12,
        position: 'relative',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08,
        shadowRadius: 8,
        elevation: 3,
    },
    removeButton: {
        position: 'absolute',
        top: 8,
        right: 8,
        padding: 4,
    },
    shareButton: {
        backgroundColor: '#0C352E',
        borderRadius: 12,
        height: 52,
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: 8,
    },
    shareButtonText: {
        color: '#FFFFFF',
        fontSize: 16,
        fontWeight: '600' as '600',
        marginLeft: 8,
    },
    // Paso 4 - Pagos
    totalAmountCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 16,
        padding: 32,
        alignItems: 'center',
        marginBottom: 24,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08,
        shadowRadius: 8,
        elevation: 3,
    },
    totalAmountLabel: {
        fontSize: 18,
        color: '#61646B',
        marginBottom: 8,
        fontWeight: '400' as '400',
    },
    totalAmountValue: {
        fontSize: 36,
        fontWeight: '700' as '700',
        color: '#232323',
    },
    paymentRow: {
        flexDirection: 'row',
        gap: 12,
        marginBottom: 12,
    },
    removePaymentButton: {
        position: 'absolute',
        top: 12,
        right: 12,
        width: 28,
        height: 28,
        borderRadius: 14,
        backgroundColor: 'transparent',
        justifyContent: 'center',
        alignItems: 'center',
        zIndex: 10,
    },
    referenceDisplayCard: {
        backgroundColor: '#F9FAFB',
        borderRadius: 8,
        padding: 16,
        marginTop: 12,
        borderWidth: 1,
        borderColor: '#E5E5E5',
    },
    referenceDisplayText: {
        fontSize: 14,
        color: '#232323',
        fontFamily: 'monospace',
        textAlign: 'center',
        letterSpacing: 1,
    },
    row: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        gap: 12,
        marginBottom: 0,
    },
    halfField: {
        flex: 1,
    },
    documentInputRow: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#FFFFFF',
        borderWidth: 1,
        borderColor: '#E5E5E5',
        borderRadius: 12,
        height: 56,
        marginBottom: 16,
    },
    documentTypeButton: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 16,
        gap: 4,
    },
    documentTypeButtonText: {
        fontSize: 16,
        color: '#232323',
        fontWeight: '500' as '500',
    },
    documentDivider: {
        width: 1,
        height: 32,
        backgroundColor: '#E5E5E5',
    },
    documentInput: {
        flex: 1,
        fontSize: 16,
        color: '#232323',
        paddingHorizontal: 12,
        height: 56,
    },
    searchIconButton: {
        width: 48,
        height: 56,
        justifyContent: 'center',
        alignItems: 'center',
    },
    clientFoundCard: {
        backgroundColor: '#F0FDF4',
        borderRadius: 12,
        padding: 16,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
        marginBottom: 24,
        borderWidth: 1,
        borderColor: '#0FE58B',
    },
    clientFoundIcon: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: '#0FE58B',
        justifyContent: 'center',
        alignItems: 'center',
    },
    clientFoundName: {
        fontSize: 16,
        color: '#0C352E',
        fontWeight: '600' as '600',
        marginBottom: 2,
    },
    clientFoundDoc: {
        fontSize: 13,
        color: '#61646B',
    },
    clientFoundChange: {
        fontSize: 14,
        color: '#0C352E',
        fontWeight: '500' as '500',
    },
    clientNotFoundCard: {
        backgroundColor: '#FFF9E6',
        borderRadius: 12,
        padding: 16,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
        marginBottom: 24,
        borderWidth: 1,
        borderColor: '#FFC107',
    },
    clientNotFoundText: {
        flex: 1,
        fontSize: 14,
        color: '#61646B',
        lineHeight: 20,
    },
    // Success screen
    successContainer: {
        flex: 1,
        backgroundColor: '#0C352E',
        justifyContent: 'center',
        alignItems: 'center',
        padding: 20,
    },
    successCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 24,
        padding: 32,
        width: '100%',
        maxWidth: 400,
        alignItems: 'center',
    },
    successIcon: {
        width: 100,
        height: 100,
        borderRadius: 50,
        backgroundColor: '#0C352E',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 24,
    },
    successTitle: {
        fontSize: 24,
        fontWeight: '700' as '700',
        color: '#232323',
        marginBottom: 12,
    },
    successSubtitle: {
        fontSize: 14,
        color: '#61646B',
        textAlign: 'center',
        marginBottom: 32,
    },
    successLabel: {
        fontSize: 14,
        color: '#61646B',
        marginBottom: 8,
        textAlign: 'center',
    },
    successAmount: {
        fontSize: 32,
        fontWeight: '700' as '700',
        color: '#232323',
        marginBottom: 24,
        textAlign: 'center',
    },
    successDividerLine: {
        width: '100%',
        height: 1,
        backgroundColor: '#E5E5E5',
        marginBottom: 24,
    },
    successDescription: {
        fontSize: 14,
        color: '#61646B',
        textAlign: 'center',
        marginBottom: 24,
    },
    successDivider: {
        width: '100%',
        paddingVertical: 20,
        borderTopWidth: 1,
        borderBottomWidth: 1,
        borderColor: '#E5E5E5',
        alignItems: 'center',
        marginBottom: 24,
    },
    totalPaidLabel: {
        fontSize: 14,
        color: '#61646B',
        marginBottom: 8,
    },
    totalPaidAmount: {
        fontSize: 28,
        fontWeight: '700' as '700',
        color: '#232323',
    },
    successDetails: {
        width: '100%',
        marginBottom: 24,
    },
    successClientName: {
        fontSize: 16,
        fontWeight: '700' as '700',
        color: '#232323',
        textAlign: 'center',
        marginBottom: 16,
    },
    detailRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        paddingVertical: 8,
    },
    detailLabel: {
        fontSize: 14,
        color: '#61646B',
    },
    detailValue: {
        fontSize: 14,
        fontWeight: '600' as '600',
        color: '#232323',
    },
    backButton2: {
        backgroundColor: '#0C352E',
        borderRadius: 12,
        height: 52,
        width: '100%',
        justifyContent: 'center',
        alignItems: 'center',
    },
    backButtonText: {
        color: '#FFFFFF',
        fontSize: 16,
        fontWeight: '600' as '600',
    },
    // Plan cards
    planCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        padding: 16,
        marginBottom: 12,
        flexDirection: 'row',
        alignItems: 'center',
        borderWidth: 2,
        borderColor: '#E5E5E5',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08,
        shadowRadius: 8,
        elevation: 3,
    },
    planCardSelected: {
        borderColor: '#0FE58B',
        backgroundColor: '#F0FFF4',
    },
    planName: {
        fontSize: 16,
        fontWeight: '600' as '600',
        color: '#232323',
        marginBottom: 4,
    },
    planDescription: {
        fontSize: 13,
        color: '#61646B',
        marginBottom: 4,
    },
    planSpeed: {
        fontSize: 12,
        color: '#0C352E',
        fontWeight: '500' as '500',
    },
    planPrice: {
        fontSize: 18,
        fontWeight: '700' as '700',
        color: '#0C352E',
    },
    // Product cards
    productCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        padding: 16,
        marginBottom: 12,
        flexDirection: 'row',
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08,
        shadowRadius: 8,
        elevation: 3,
    },
    productSelectCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        padding: 16,
        marginBottom: 12,
        flexDirection: 'row',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#E5E5E5',
    },
    productName: {
        fontSize: 15,
        fontWeight: '600' as '600',
        color: '#232323',
        marginBottom: 4,
    },
    productType: {
        fontSize: 12,
        color: '#61646B',
        marginBottom: 4,
    },
    productDescription: {
        fontSize: 13,
        color: '#61646B',
    },
    productPrice: {
        fontSize: 14,
        fontWeight: '600' as '600',
        color: '#0C352E',
    },
    quantityButton: {
        width: 32,
        height: 32,
        borderRadius: 16,
        backgroundColor: '#F5F5F5',
        justifyContent: 'center',
        alignItems: 'center',
    },
    quantityText: {
        fontSize: 16,
        fontWeight: '600' as '600',
        color: '#232323',
        minWidth: 30,
        textAlign: 'center',
    },
    emptyCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        padding: 24,
        alignItems: 'center',
        marginBottom: 16,
    },
    emptyText: {
        fontSize: 14,
        color: '#61646B',
        textAlign: 'center',
    },
    totalRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        width: '100%',
        marginBottom: 8,
    },
    totalValue: {
        fontSize: 16,
        fontWeight: '600' as '600',
        color: '#232323',
    },
    // Selector de tipo de documento
    documentTypeContainer: {
        flexDirection: 'row',
        gap: 8,
        marginBottom: 16,
        flexWrap: 'wrap',
    },
    documentTypeChip: {
        paddingHorizontal: 16,
        paddingVertical: 8,
        borderRadius: 8,
        backgroundColor: '#F5F5F5',
        borderWidth: 1,
        borderColor: '#E5E5E5',
    },
    documentTypeChipActive: {
        backgroundColor: '#0C352E',
        borderColor: '#0C352E',
    },
    documentTypeText: {
        fontSize: 14,
        fontWeight: '600' as '600',
        color: '#61646B',
    },
    documentTypeTextActive: {
        color: '#FFFFFF',
    },
    // Card de cobertura mejorada
    coverageCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        padding: 16,
        marginTop: 16,
        flexDirection: 'row',
        alignItems: 'flex-start',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
        borderWidth: 1,
        borderColor: '#E5E5E5',
    },
    coverageCloseIcon: {
        width: 32,
        height: 32,
        borderRadius: 16,
        borderWidth: 1,
        borderColor: '#E5E5E5',
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 12,
    },
    coverageContent: {
        flex: 1,
    },
    coverageTitle: {
        fontSize: 14,
        fontWeight: '600' as '600',
        color: '#232323',
        marginBottom: 4,
    },
    coverageSubtext: {
        fontSize: 12,
        color: '#61646B',
        lineHeight: 18,
    },
    // Canvas de firma
    signatureButton: {
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        padding: 20,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 12,
        borderWidth: 2,
        borderColor: '#E5E5E5',
        borderStyle: 'dashed',
    },
    signatureButtonText: {
        fontSize: 16,
        fontWeight: '600' as '600',
        color: '#0C352E',
    },
    signaturePreview: {
        backgroundColor: '#F0FDF4',
        borderRadius: 12,
        padding: 20,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 12,
        borderWidth: 1,
        borderColor: '#0FE58B',
    },
    signaturePreviewText: {
        fontSize: 16,
        fontWeight: '600' as '600',
        color: '#0C352E',
    },
    signatureTitle: {
        fontSize: 18,
        fontWeight: '600' as '600',
        color: '#232323',
    },
    signatureCancelText: {
        fontSize: 16,
        color: '#61646B',
    },
    signatureClearText: {
        fontSize: 16,
        color: '#0C352E',
        fontWeight: '600' as '600',
    },
    signatureSection: {
        marginTop: 16,
    },
    signatureHeader: {
        flexDirection: 'row',
        justifyContent: 'flex-end',
        marginBottom: 8,
        minHeight: 24,
    },
    signatureClearButton: {
        color: '#61646B',
        fontSize: 14,
        fontWeight: '500' as '500',
    },
    signatureCanvas: {
        backgroundColor: '#F5F5F5',
        borderRadius: 12,
        height: 200,
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#E5E5E5',
        borderStyle: 'solid',
    },
    signatureCanvasLarge: {
        backgroundColor: '#F9FAFB',
        borderRadius: 12,
        height: 240,
        overflow: 'hidden',
    },
    signatureDrawArea: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    signatureDrawn: {
        fontSize: 48,
        color: '#232323',
        fontStyle: 'italic',
    },
    signatureLine: {
        width: '100%',
        height: 2,
        backgroundColor: '#232323',
    },
    signatureHeaderRight: {
        flexDirection: 'row',
        justifyContent: 'flex-end',
        marginBottom: 8,
    },
    signatureEmptyContainer: {
        width: '100%',
        alignItems: 'center',
    },
    signaturePreviewContainer: {
        width: '100%',
        alignItems: 'center',
    },
    // Paso de Pago
    // Estilos adicionales para modal de confirmación
    successModal: {
        flex: 1,
        backgroundColor: 'rgba(12, 53, 46, 0.95)',
        justifyContent: 'center',
        alignItems: 'center',
        padding: 20,
    },
    successDetailRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        width: '100%',
        marginBottom: 12,
    },
    successDetailLabel: {
        fontSize: 14,
        color: '#61646B',
    },
    successDetailValue: {
        fontSize: 14,
        fontWeight: '600' as '600',
        color: '#232323',
    },
    successButton: {
        backgroundColor: '#0C352E',
        paddingVertical: 16,
        paddingHorizontal: 32,
        borderRadius: 12,
        width: '100%',
        alignItems: 'center',
    },
    successButtonText: {
        color: '#FFFFFF',
        fontSize: 16,
        fontWeight: '600' as '600',
    },
    // Modales de selección
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        justifyContent: 'center',
        alignItems: 'center',
        padding: 20,
    },
    modalContent: {
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        width: '80%',
        maxWidth: 300,
        overflow: 'hidden',
    },
    modalOption: {
        paddingVertical: 16,
        paddingHorizontal: 20,
        borderBottomWidth: 1,
        borderBottomColor: '#F0F0F0',
    },
    modalOptionText: {
        fontSize: 16,
        color: '#232323',
        textAlign: 'center',
    },
    // Botón del mapa
    mapButton: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#FFFFFF',
        borderWidth: 1,
        borderColor: '#E5E7EB',
        borderRadius: 12,
        paddingVertical: 16,
        paddingHorizontal: 16,
        marginBottom: 16,
    },
    mapButtonText: {
        flex: 1,
        fontSize: 14,
        color: '#232323',
    },
    // Acciones del modal del mapa
    mapActions: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        flexDirection: 'row',
        backgroundColor: '#FFFFFF',
        padding: 16,
        gap: 12,
        borderTopWidth: 1,
        borderTopColor: '#E5E7EB',
    },
    mapActionButton: {
        flex: 1,
        paddingVertical: 14,
        borderRadius: 12,
        alignItems: 'center',
    },
    cancelButton: {
        backgroundColor: '#F3F4F6',
    },
    cancelButtonText: {
        color: '#6B7280',
        fontSize: 16,
        fontWeight: '600' as '600',
    },
    confirmButton: {
        backgroundColor: '#0C352E',
    },
    confirmButtonText: {
        color: '#FFFFFF',
        fontSize: 16,
        fontWeight: '600' as '600',
    },
});
