import { StyleSheet, Dimensions, Platform } from "react-native";

const { width } = Dimensions.get('window');

export const sales_styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#F5F5F5',
    },
    header: {
        backgroundColor: '#0C352E',
        paddingVertical: 16,
        paddingHorizontal: 20,
        flexDirection: 'row',
        alignItems: 'center',
    },
    backButton: {
        padding: 4,
        marginRight: 12,
    },
    stepIndicatorContainer: {
        width: 72,
        height: 72,
        marginRight: 16,
        position: 'relative',
        justifyContent: 'center',
        alignItems: 'center',
    },
    stepIconContainer: {
        position: 'absolute',
        justifyContent: 'center',
        alignItems: 'center',
        top: 14,
    },
    stepNumber: {
        position: 'absolute',
        bottom: 14,
        fontSize: 10,
        color: '#FFFFFF',
        fontWeight: '600' as '600',
    },
    headerTextContainer: {
        flex: 1,
    },
    headerTitle: {
        fontSize: 20,
        fontWeight: '600' as '600',
        color: '#FFFFFF',
        marginBottom: 2,
    },
    headerSubtitle: {
        fontSize: 13,
        color: 'rgba(255, 255, 255, 0.9)',
    },
    content: {
        flex: 1,
    },
    form: {
        padding: 20,
    },
    field: {
        marginBottom: 16,
    },
    label: {
        fontSize: 13,
        color: '#61646B',
        marginBottom: 8,
    },
    input: {
        backgroundColor: '#FFFFFF',
        borderWidth: 1,
        borderColor: '#E5E5E5',
        borderRadius: 12,
        paddingHorizontal: 16,
        height: 50,
        fontSize: 15,
        color: '#232323',
    },
    mapContainer: {
        height: 300,
        backgroundColor: '#E5E5E5',
        borderRadius: 12,
        overflow: Platform.OS === 'android' ? 'visible' : 'hidden',
        marginBottom: 16,
    },
    markerIcon: {
        width: 50,
        height: 50,
        borderRadius: 25,
        backgroundColor: '#0C352E',
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
        elevation: 5,
    },
    alertCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        padding: 16,
        flexDirection: 'row',
        alignItems: 'flex-start',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08,
        shadowRadius: 8,
        elevation: 3,
    },
    alertIconContainer: {
        width: 44,
        height: 44,
        borderRadius: 22,
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 12,
    },
    alertTextContainer: {
        flex: 1,
    },
    alertTitle: {
        fontSize: 14,
        fontWeight: '600' as '600',
        color: '#232323',
        marginBottom: 4,
    },
    alertDescription: {
        fontSize: 13,
        color: '#61646B',
        lineHeight: 18,
    },
    buttonContainer: {
        padding: 20,
        backgroundColor: '#F5F5F5',
    },
    nextButton: {
        backgroundColor: '#0C352E',
        borderRadius: 12,
        height: 52,
        justifyContent: 'center',
        alignItems: 'center',
    },
    nextButtonText: {
        color: '#FFFFFF',
        fontSize: width * 0.04,
        fontWeight: '600',
    },
    headerContent: {
        flex: 1,
        alignItems: 'center',
    },
    stepIndicator: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    stepText: {
        color: '#FFFFFF',
        fontSize: 14,
        fontWeight: '500',
    },
    alertIcon: {
        marginRight: 8,
    },
    alertText: {
        color: '#FFFFFF',
        fontSize: 14,
    },
    textArea: {
        height: 120,
        paddingTop: 12,
        textAlignVertical: 'top',
    },
    inputWithIcon: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#FFFFFF',
        borderWidth: 1,
        borderColor: '#E5E5E5',
        borderRadius: 8,
        paddingHorizontal: 16,
        height: 50,
    },
    inputText: {
        flex: 1,
        fontSize: 14,
        color: '#232323',
    },
    pickerSmall: {
        width: 80,
        height: 48,
    },
    phoneInput: {
        flex: 1,
        fontSize: 14,
        color: '#232323',
        paddingHorizontal: 12,
    },
    pickerContainer: {
        flexDirection: 'row',
        backgroundColor: '#FFFFFF',
        borderWidth: 1,
        borderColor: '#E5E5E5',
        borderRadius: 12,
        height: 50,
        overflow: 'hidden',
    },
    picker: {
        flex: 1,
        height: 48,
    },
    signatureContainer: {
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        padding: 16,
        marginBottom: 20,
    },
    signatureHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 12,
    },
    clearButton: {
        fontSize: 14,
        color: '#61646B',
    },
    totalCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        padding: 24,
        alignItems: 'center',
        marginBottom: 20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08,
        shadowRadius: 8,
        elevation: 3,
    },
    totalLabel: {
        fontSize: 16,
        color: '#61646B',
        marginBottom: 8,
    },
    totalAmount: {
        fontSize: 28,
        fontWeight: '700' as '700',
        color: '#232323',
    },
    paymentsHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 16,
    },
    paymentsTitle: {
        fontSize: 16,
        fontWeight: '600' as '600',
        color: '#232323',
    },
    addPaymentButton: {
        width: 32,
        height: 32,
        borderRadius: 16,
        borderWidth: 2,
        borderColor: '#232323',
        justifyContent: 'center',
        alignItems: 'center',
    },
    paymentCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        padding: 16,
        marginBottom: 12,
        position: 'relative',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08,
        shadowRadius: 8,
        elevation: 3,
    },
    removeButton: {
        position: 'absolute',
        top: 8,
        right: 8,
        padding: 4,
    },
    shareButton: {
        backgroundColor: '#0C352E',
        borderRadius: 12,
        height: 52,
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: 8,
    },
    shareButtonText: {
        color: '#FFFFFF',
        fontSize: 16,
        fontWeight: '600' as '600',
        marginLeft: 8,
    },
    row: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 12,
    },
    halfField: {
        width: '48%',
    },
    // Success screen
    successContainer: {
        flex: 1,
        backgroundColor: '#0C352E',
        justifyContent: 'center',
        alignItems: 'center',
        padding: 20,
    },
    successCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 24,
        padding: 32,
        width: '100%',
        maxWidth: 400,
        alignItems: 'center',
    },
    successIcon: {
        width: 100,
        height: 100,
        borderRadius: 50,
        backgroundColor: '#0C352E',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 24,
    },
    successTitle: {
        fontSize: 24,
        fontWeight: '700' as '700',
        color: '#232323',
        marginBottom: 12,
    },
    successDescription: {
        fontSize: 14,
        color: '#61646B',
        textAlign: 'center',
        marginBottom: 24,
    },
    successDivider: {
        width: '100%',
        paddingVertical: 20,
        borderTopWidth: 1,
        borderBottomWidth: 1,
        borderColor: '#E5E5E5',
        alignItems: 'center',
        marginBottom: 24,
    },
    totalPaidLabel: {
        fontSize: 14,
        color: '#61646B',
        marginBottom: 8,
    },
    totalPaidAmount: {
        fontSize: 28,
        fontWeight: '700' as '700',
        color: '#232323',
    },
    successDetails: {
        width: '100%',
        marginBottom: 24,
    },
    successName: {
        fontSize: 16,
        fontWeight: '700' as '700',
        color: '#232323',
        textAlign: 'center',
        marginBottom: 16,
    },
    detailRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        paddingVertical: 8,
    },
    detailLabel: {
        fontSize: 14,
        color: '#61646B',
    },
    detailValue: {
        fontSize: 14,
        fontWeight: '600' as '600',
        color: '#232323',
    },
    backButton2: {
        backgroundColor: '#0C352E',
        borderRadius: 12,
        height: 52,
        width: '100%',
        justifyContent: 'center',
        alignItems: 'center',
    },
    backButtonText: {
        color: '#FFFFFF',
        fontSize: 16,
        fontWeight: '600' as '600',
    },
});
